# Generated by Django 4.2.6 on 2023-11-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('apellido', models.CharField(max_length=256)),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('telefono', models.CharField(max_length=20)),
                ('camada', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('apellido', models.CharField(max_length=256)),
                ('cantidad_puntos', models.PositiveIntegerField()),
                ('torneos_jugados', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_torneo', models.CharField(max_length=256)),
                ('ciudad', models.CharField(max_length=256)),
                ('fecha_comienzo', models.DateField()),
                ('superficie', models.CharField(max_length=256)),
                ('modalidad', models.CharField(max_length=256)),
            ],
        ),
    ]
