# Generated by Django 4.2.6 on 2023-11-08 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_estudios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneo',
            name='ciudad',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='modalidad',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='superficie',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
