# Generated by Django 4.2.6 on 2023-11-09 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_estudios', '0002_alter_torneo_ciudad_alter_torneo_modalidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='camada',
        ),
    ]
